# Generated by Django 4.2.6 on 2023-11-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventID',
            fields=[
                ('event_name', models.CharField(max_length=40)),
                ('event_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='venue_details',
            fields=[
                ('venue_room', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('venue_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_event_form_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('form_svg', models.FileField(upload_to='')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
            ],
        ),
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj', models.BooleanField()),
                ('pa', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
            ],
        ),
        migrations.CreateModel(
            name='event_venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
                ('venue_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.venue_details')),
            ],
        ),
        migrations.CreateModel(
            name='event_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
            ],
        ),
        migrations.CreateModel(
            name='event_sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_letter', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
            ],
        ),
        migrations.CreateModel(
            name='event_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
            ],
        ),
        migrations.CreateModel(
            name='event_coordinators_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_name', models.CharField(max_length=40)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
            ],
        ),
        migrations.CreateModel(
            name='event_coordinators',
            fields=[
                ('coord_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventid')),
            ],
        ),
    ]
