# Generated by Django 4.2.6 on 2023-11-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_details',
            name='venue_room',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
